# Generated by Django 4.1 on 2022-08-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(null=True)),
                ('is_published', models.BooleanField(null=True)),
            ],
        ),
    ]
