# Generated by Django 4.1 on 2022-08-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
