# Generated by Django 4.1 on 2022-08-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
