# Generated by Django 4.1 on 2022-08-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_streamplatform_slug_watchlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='summary',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
