# Generated by Django 4.1 on 2022-08-28 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_alter_watchlist_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.streamplatform'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='summary',
            field=models.TextField(blank=True, max_length=1050, null=True),
        ),
    ]
