# Generated by Django 4.1 on 2022-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0013_alter_review_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='no_of_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
