# Generated by Django 4.1 on 2022-09-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0014_watchlist_no_of_reviews_watchlist_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='rating',
            new_name='average_rating',
        ),
    ]
