# Generated by Django 4.1 on 2022-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0016_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/streams/images'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/watchlist/images'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='uploads/watchlist/videos'),
        ),
    ]
