# Generated by Django 4.1 on 2022-10-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0017_streamplatform_image_watchlist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='streams/images'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watchlist/images'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='watchlist/videos'),
        ),
    ]
