# Generated by Django 4.1 on 2022-10-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0020_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
