# Generated by Django 4.1 on 2022-10-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0025_remove_watchlist_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_on',
        ),
    ]
