# Generated by Django 4.1 on 2022-10-05 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist', '0027_review_created_on_review_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ('date_created',)},
        ),
        migrations.CreateModel(
            name='UsersWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlists', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(to='watchlist.watchlist')),
            ],
        ),
    ]
