# Generated by Django 4.1 on 2022-10-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0028_alter_review_options_alter_watchlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userswatchlist',
            name='watchlist',
            field=models.ManyToManyField(related_name='users_watchlist', to='watchlist.watchlist'),
        ),
    ]
