# Generated by Django 4.1 on 2022-10-06 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist', '0029_alter_userswatchlist_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userswatchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userswatchlist',
            name='watchlist',
            field=models.ManyToManyField(to='watchlist.watchlist'),
        ),
    ]
